### ISSUE TITLE
While using product-merge.sh

### ISSUE THREAD

**Issue by ApexLegend007** [rain2wood/erofs#6]
siddhant@siddhant-HP-Pavilion-x360-Convertible-14-dh1xxx:~/Desktop/oplus-utils$ sudo ./product-merge.sh 
[sudo] password for siddhant:              
[INFO] Cleaning up existing build residue
[INFO] Merging my_product into product.img
[INFO] Merging my_engineering into product.img
[INFO] Merging my_company into product.img
[INFO] Merging my_carrier into product.img
[INFO] Merging my_region into product.img
[INFO] Merging my_heytap into product.img
[INFO] Merging my_stock into product.img
[INFO] Merging my_preload into product.img
[INFO] Merging my_bigball into product.img
[INFO] Merging my_manifest into product.img
[INFO] Cleaning product image
[INFO] Grabbing file contexts
[INFO] Setting image size
[INFO] Rebuilding Product image
Traceback (most recent call last):
  File "/home/siddhant/Desktop/oplus-utils/tools/mkuserimg_mke2fs.py", line 214, in <module>
    main(sys.argv[1:])
  File "/home/siddhant/Desktop/oplus-utils/tools/mkuserimg_mke2fs.py", line 184, in main
    mke2fs_cmd, e2fsdroid_cmd = ConstructE2fsCommands(args)
  File "/home/siddhant/Desktop/oplus-utils/tools/mkuserimg_mke2fs.py", line 165, in ConstructE2fsCommands
    blocks = int(args.fs_size) / BLOCKSIZE
ValueError: invalid literal for int() with base 10: '3.04907e+09'

**Comment by rain2wood** [comment]
OnePlus 9 Pro?

**Comment by ApexLegend007** [comment]
Nope it's OnePlus 9R

**Comment by ApexLegend007** [comment]
> OnePlus 9 Pro?

OnePlus 9R

**Comment by jordanyoong1** [comment]
Same problem aswell, I'm using GT Neo2's RUI3.0

**Comment by rain2wood** [comment]
9R Probably doesn't need product_merge.
Product merge is only useful when your product image is a dummy image.

**Comment by ApexLegend007** [comment]
> 9R Probably doesn't need product_merge. Product merge is only useful when your product image is a dummy image.
> 
> So far, only 9 Pro needed product merge.

I see 🙂
